In [2]:
# IMPORT PYTHON LIBRARY 
import numpy as np
import pandas as pd

In [4]:
A = np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
B = np.array([[1,2],[3,4]])

In [7]:
B

array([[1, 2],
       [3, 4]])

In [9]:
B[:,0]

array([1, 3])

In [10]:
B[0,:]

array([1, 2])

In [11]:
C = np.array([[10,20],[30,40]])
C

array([[10, 20],
       [30, 40]])

In [12]:
B * C

array([[ 10,  40],
       [ 90, 160]])

In [13]:
B + C

array([[11, 22],
       [33, 44]])